version: '3.7'
services:
  mongodb:
    container_name: mongodb_smarthero
    image: mongo:latest
    env_file:
      - ../api/.env  
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    restart: always
volumes:
  mongodb_data_container: